# Recurrent Neural Networks (RNN): Long short-term memory (LSTM)

## Table of contents

### [1. Libraries import and Data preparation](#1)
#### [- Droping the 3 weather stations not included in answers](#1.1)
#### [- Removing the 2 types of observations missing multiple entries for most stations](#1.2)
#### [- Filling in 3 individual observations assuming nearby stations have similar weather conditions](#1.3)

### [2. RNN](#2)
#### [2.1 Reshaping the data ](#2.1)
#### [2.2 Spliting the data into training ant testing sets](#2.2)
#### [2.3 Running the model](#2.3)
##### [- 1st iteration](#2.3.1)
##### [- 2nd iteration](#2.3.2)
##### [- 3rd iteration](#2.3.3)
##### [- 4th iteration](#2.3.4)
##### [- 5th iteration](#2.3.5)

## 1. Libraries import and Data preparation
<div id='1'></div>

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from numpy import unique
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split



##to ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Creating paths to the data folder of the project and to the folder for saving the charts
path_data = r"C:\Users\dacol\Documents\Data_Project_careerfoundry\ClimateWins_ML\02 Data"

# Importing the unscaled dataframe
df_weather = pd.read_csv(os.path.join(path_data,'Original Data','Dataset-weather-prediction-dataset-processed.csv'), sep =',')

# Importing the rated dataframe for pleasant days
df_rate = pd.read_csv(os.path.join(path_data,'Original Data','Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'), sep =',')

In [5]:
print(df_weather.shape)
print(df_rate.shape)

(22950, 170)
(22950, 16)

In [6]:
df_weather.describe()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
count,2.295000e+04,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,...,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000
mean,1.990984e+07,6.509630,5.410763,2.120462,0.758554,1.018013,1.345244,0.222305,0.359564,4.592222,...,5.723355,0.825824,1.014242,1.134490,0.414698,0.001220,3.460989,10.724257,7.901904,13.515752
std,1.813833e+05,3.443672,2.406115,0.732625,0.110699,0.006543,0.931158,0.498995,2.006231,4.310808,...,1.630313,0.071121,0.010727,0.848813,0.844943,0.049383,3.329432,3.328727,3.659393,3.477373
min,1.960010e+07,1.000000,0.000000,0.000000,0.350000,0.974700,0.010000,0.000000,-2.000000,0.000000,...,0.000000,0.380000,0.955100,0.020000,0.000000,0.000000,0.000000,-3.500000,-7.300000,-1.500000
25%,1.975092e+07,4.000000,4.000000,2.100000,0.680000,1.015800,0.540000,0.000000,0.000000,0.400000,...,5.000000,0.790000,1.009400,0.400000,0.010000,0.000000,0.500000,8.800000,6.100000,11.300000
50%,1.991060e+07,7.000000,6.000000,2.100000,0.770000,1.018000,1.130000,0.000000,0.000000,3.600000,...,6.000000,0.820000,1.014200,0.970000,0.280000,0.000000,3.400000,10.700000,7.900000,13.500000
75%,2.007021e+07,9.000000,7.000000,2.100000,0.840000,1.020100,2.070000,0.220000,0.000000,7.900000,...,7.000000,0.870000,1.020900,1.700000,0.410000,0.000000,4.800000,13.000000,10.300000,15.700000
max,2.022103e+07,12.000000,8.000000,16.300000,1.000000,1.045200,4.560000,8.500000,49.000000,16.800000,...,8.000000,1.000000,1.046300,3.980000,90.000000,3.000000,15.800000,23.600000,19.500000,28.400000

#### - Droping the 3 weather stations not included in answers
<div id='1.2'></div>

In [8]:
#isolating the columns names from the rate df since some weather stations are missing
rate_columns = df_rate.columns.to_list()
rate_columns

['DATE',
 'BASEL_pleasant_weather',
 'BELGRADE_pleasant_weather',
 'BUDAPEST_pleasant_weather',
 'DEBILT_pleasant_weather',
 'DUSSELDORF_pleasant_weather',
 'HEATHROW_pleasant_weather',
 'KASSEL_pleasant_weather',
 'LJUBLJANA_pleasant_weather',
 'MAASTRICHT_pleasant_weather',
 'MADRID_pleasant_weather',
 'MUNCHENB_pleasant_weather',
 'OSLO_pleasant_weather',
 'SONNBLICK_pleasant_weather',
 'STOCKHOLM_pleasant_weather',
 'VALENTIA_pleasant_weather']

In [9]:
#isolating the weather columns to check for the stations to trim
weather_columns = df_weather.columns.to_list()
weather_columns

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_wind_speed',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_snow_depth',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_wind_speed',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_snow_depth',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'GDANSK_cloud_cover',
 'GDANSK_humidity',
 'GDANSK_precipitation',
 'GDANSK_snow_depth',
 'GDANSK_temp_mean',
 'GDANSK_temp_min',
 'GDANSK_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_snow_depth',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_wind_speed',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_wind_speed',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_wind_speed',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_wind_speed',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_snow_depth',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_wind_speed',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_snow_depth',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'ROMA_cloud_cover',
 'ROMA_wind_speed',
 'ROMA_humidity',
 'ROMA_pressure',
 'ROMA_sunshine',
 'ROMA_temp_mean',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_wind_speed',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'TOURS_wind_speed',
 'TOURS_humidity',
 'TOURS_pressure',
 'TOURS_global_radiation',
 'TOURS_precipitation',
 'TOURS_temp_mean',
 'TOURS_temp_min',
 'TOURS_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_snow_depth',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [10]:
#splitting the column names to isolate the stations names
answer_stations = [col.split('_')[0] for col in rate_columns if '_' in col ]
answer_stations

['BASEL',
 'BELGRADE',
 'BUDAPEST',
 'DEBILT',
 'DUSSELDORF',
 'HEATHROW',
 'KASSEL',
 'LJUBLJANA',
 'MAASTRICHT',
 'MADRID',
 'MUNCHENB',
 'OSLO',
 'SONNBLICK',
 'STOCKHOLM',
 'VALENTIA']

In [11]:
#keeping only the weather stations maatching the stations from the rates
weather_stations = [col for col in weather_columns if col.split('_')[0] in answer_stations]
weather_stations

['BASEL_cloud_cover',
 'BASEL_wind_speed',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_snow_depth',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_wind_speed',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_snow_depth',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_snow_depth',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_wind_speed',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_wind_speed',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_wind_speed',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_wind_speed',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_snow_depth',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_wind_speed',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_snow_depth',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_wind_speed',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_snow_depth',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [12]:
#creating a new df with the desired columns
df_weather_new = df_weather[weather_stations]
df_weather_new.head()

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

#### - Removing the 2 types of observations missing multiple entries for most stations
<div id='1.2'></div>

In [14]:
#Extract the part of the column names after the underscore
column_names = [col.split('_', 1)[1] for col in df_weather.columns if '_' in col]

# Remove duplicates by converting the list to a set and then back to a list
unique_column_names = list(set(column_names))

# Display the list of unique column names
unique_column_names

['temp_min',
 'temp_max',
 'global_radiation',
 'wind_speed',
 'sunshine',
 'precipitation',
 'pressure',
 'humidity',
 'snow_depth',
 'cloud_cover',
 'temp_mean']

In [15]:
# Create a dictionary to store the count of stations for each observation type
station_counts = {}

for obs in unique_column_names:
    # Select columns related to the current observation type
    columns = [col for col in df_weather_new.columns if col.endswith(obs)]
    
    # Count the number of stations (i.e., the number of columns) for the current observation type
    station_counts[obs] = len(columns)

# Print the count of stations for each observation type
print("Number of stations covered by each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Number of stations covered by each observation type:
temp_min: 15 stations
temp_max: 15 stations
global_radiation: 15 stations
wind_speed: 9 stations
sunshine: 15 stations
precipitation: 15 stations
pressure: 14 stations
humidity: 14 stations
snow_depth: 6 stations
cloud_cover: 14 stations
temp_mean: 15 stations

In [16]:
# Identify the two observation types with the minimum counts
observations_to_remove = sorted(station_counts, key=station_counts.get)[:2]
observations_to_remove

['snow_depth', 'wind_speed']

In [17]:
# Matching the columns to remove
columns_to_remove = [col for col in df_weather_new.columns if any(col.endswith(obs) for obs in observations_to_remove)]
columns_to_remove

['BASEL_wind_speed',
 'BASEL_snow_depth',
 'DEBILT_wind_speed',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_snow_depth',
 'HEATHROW_snow_depth',
 'KASSEL_wind_speed',
 'LJUBLJANA_wind_speed',
 'MAASTRICHT_wind_speed',
 'MADRID_wind_speed',
 'MUNCHENB_snow_depth',
 'OSLO_wind_speed',
 'OSLO_snow_depth',
 'SONNBLICK_wind_speed',
 'VALENTIA_snow_depth']

In [18]:
# Remove these observation types from the dataframe
df_weather_new_cleaned = df_weather_new.drop(columns=columns_to_remove)
df_weather_new_cleaned.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

#### - Filling in 3 individual observations assuming nearby stations have similar weather conditions
<div id='1.3'></div>

In [20]:
# Create a list of all unique station names in the dataset

all_stations = set([col.split('_')[0] for col in df_weather_new_cleaned.columns if '_' in col])
all_stations

{'BASEL',
 'BELGRADE',
 'BUDAPEST',
 'DEBILT',
 'DUSSELDORF',
 'HEATHROW',
 'KASSEL',
 'LJUBLJANA',
 'MAASTRICHT',
 'MADRID',
 'MUNCHENB',
 'OSLO',
 'SONNBLICK',
 'STOCKHOLM',
 'VALENTIA'}

In [21]:
# Find the missing stations for the weather observations observations

observation_types = unique_column_names
missing_stations_by_observation = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in df_weather_new_cleaned.columns if col.endswith(obs)]
    
    # Extract station names by removing the observation type from the column names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identify stations that are in all_stations but missing from the current observation type
    missing_stations = all_stations - station_names
    
    # Store the missing station names in the dictionary only if exactly one station is missing
    if len(missing_stations) == 1:
        missing_stations_by_observation[obs] = missing_stations

# Print the missing station names for each observation type
for obs, missing_stations in missing_stations_by_observation.items():
    print(f"\nStations missing from {obs}:")
    for station in missing_stations:
        print(station)

Stations missing from pressure:
MUNCHENB

Stations missing from humidity:
STOCKHOLM

Stations missing from cloud_cover:
KASSEL

**Assuming nearby stations have similar weather, we pick one to copy the data from (Ljubljana is near Kassel, Sonnblick is near Munchen, and Oslo is close enough to Stockholm**

In [23]:
# Define the mapping of stations to copy observations from
station_mapping = {
    'KASSEL_cloud_cover': 'LJUBLJANA_cloud_cover',
    'STOCKHOLM_humidity': 'OSLO_humidity',
    'MUNCHENB_pressure': 'SONNBLICK_pressure'
}

# Create the new columns and copy the corresponding weather observations
for target, source in station_mapping.items():
    df_weather_new_cleaned[target] = df_weather_new_cleaned[source]

# Reorder the columns to group observations by weather station
ordered_columns = []
stations = sorted(set(col.split('_')[0] for col in df_weather_new_cleaned.columns))

for station in stations:
    station_columns = [col for col in df_weather_new_cleaned.columns if col.startswith(station)]
    ordered_columns.extend(station_columns)

df_weather_new_cleaned = df_weather_new_cleaned[ordered_columns]

# Display the updated dataframe
df_weather_new_cleaned.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_humidity,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,0.98,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,0.62,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,0.69,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,0.98,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,0.96,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [24]:
#Saving the cleaned data set for future reference and use in models

df_weather_new_cleaned.to_pickle(os.path.join(path_data, 'Prepared Data', 'Cleaned_ML_ready.pkl' ))

In [25]:
# Droping the date variable from the rates (pleasant/unpleasant)

df_rate.drop(columns = 'DATE', inplace = True)

In [26]:
# Renaming dataframes as X and y
X, y = df_weather_new_cleaned, df_rate

# Display the shapes of X and y
print(X.shape, y.shape)

(22950, 135) (22950, 15)

## 2. RNN
<div id='2'></div>

### 2.1 Reshaping the data 
<div id='2.1'></div>

In [117]:
# Turn X and y from a df to arrays

X = np.array(X)
y = np.array(y)

In [118]:
# reshaping X to a 3D object
X = X.reshape(-1,15,9)

In [119]:
# Verifying the shape of X

X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   1.0114,   0.05  , ...,   2.2   ,   4.9   ,
           0.98  ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   1.0114,   0.05  , ...,   3.    ,   5.    ,
           0.62  ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   1.0114,   0.05  , ...,   1.3   ,   4.1   ,
           0.69  ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   1.0059,   1.11  , ...,  12.1   ,  14.4   ,
           0.85  ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   1.016 ,   1.11  , ...,   5.1   ,  12.4   ,
           0.94  ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   1.0164,   1.11  , ...,   5.    ,  12.6   ,
           0.97  ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

### 2.2 Spliting the data into training ant testing sets
<div id='2.2'></div>

In [121]:
#Split data into training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [122]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16065, 15, 9)
(6885, 15, 9)
(16065, 15)
(6885, 15)

### 2.3 Running the model
<div id='2.3'></div>

In [124]:
# Create a dictionary from the list
stations = {index: station for index, station in enumerate(all_stations)}

# Display the dictionary
stations

{0: 'BUDAPEST',
 1: 'MAASTRICHT',
 2: 'DUSSELDORF',
 3: 'VALENTIA',
 4: 'STOCKHOLM',
 5: 'HEATHROW',
 6: 'MADRID',
 7: 'DEBILT',
 8: 'BASEL',
 9: 'OSLO',
 10: 'SONNBLICK',
 11: 'MUNCHENB',
 12: 'BELGRADE',
 13: 'KASSEL',
 14: 'LJUBLJANA'}

#### - 1st iteration
<div id='2.3.1'></div>

In [126]:
# 1st iteration

epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh'))

In [127]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                        │ (None, 32)                  │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 15)                  │             495 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,871 (22.93 KB)

 Trainable params: 5,871 (22.93 KB)

 Non-trainable params: 0 (0.00 B)

In [128]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [129]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.2281 - loss: 24.1800 - val_accuracy: 0.5644 - val_loss: 28.7941
Epoch 2/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.1926 - loss: 24.5173 - val_accuracy: 0.0633 - val_loss: 24.7777
Epoch 3/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.1162 - loss: 23.9388 - val_accuracy: 0.5893 - val_loss: 27.6070
Epoch 4/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1454 - loss: 24.4903 - val_accuracy: 0.1897 - val_loss: 31.9207
Epoch 5/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0924 - loss: 24.5360 - val_accuracy: 0.1069 - val_loss: 30.0269
Epoch 6/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.1229 - loss: 23.1715 - val_accuracy: 0.0353 - val_loss: 28.0652
Epoch 7/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1006 - loss: 23.0441 - val_accuracy: 0.0119 - val_loss: 23.8975
Epoch 8/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1450 - loss: 23.5700 - val_accuracy: 0.3646 - val_loss: 19.2122
Epoch 9/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2327 - loss: 22.5419 - val_accuracy: 0.6148 - val_loss: 30.9948
Epoch 10/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2531 - loss: 22.5522 - val_accuracy: 0.6325 - val_loss: 27.9179
Epoch 11/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2872 - loss: 22.0406 - val_accuracy: 0.6336 - val_loss: 15.8047
Epoch 12/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3215 - loss: 22.6404 - val_accuracy: 0.6177 - val_loss: 25.7320
Epoch 13/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2850 - loss: 24.7417 - val_accuracy: 0.5978 - val_loss: 25.2916
Epoch 14/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2441 - loss: 23.8419 - val_accuracy: 0.6087 - val_loss: 32.5993
Epoch 15/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2633 - loss: 23.5198 - val_accuracy: 0.6295 - val_loss: 15.5235
Epoch 16/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2963 - loss: 22.9561 - val_accuracy: 0.6193 - val_loss: 29.0129
Epoch 17/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3208 - loss: 23.4702 - val_accuracy: 0.6301 - val_loss: 28.2857
Epoch 18/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2859 - loss: 24.8043 - val_accuracy: 0.6395 - val_loss: 29.3316
Epoch 19/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2648 - loss: 24.4098 - val_accuracy: 0.6333 - val_loss: 26.6182
Epoch 20/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2250 - loss: 23.1342 - val_accuracy: 0.6187 - val_loss: 15.9076
Epoch 21/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.2666 - loss: 22.6818 - val_accuracy: 0.6315 - val_loss: 15.7119
Epoch 22/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.2724 - loss: 22.8064 - val_accuracy: 0.6302 - val_loss: 24.3347
Epoch 23/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2769 - loss: 22.3579 - val_accuracy: 0.6351 - val_loss: 17.9469
Epoch 24/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2744 - loss: 23.3209 - val_accuracy: 0.6247 - val_loss: 15.8565
Epoch 25/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2740 - loss: 22.9951 - val_accuracy: 0.6009 - val_loss: 32.5336
Epoch 26/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2626 - loss: 23.3928 - val_accuracy: 0.6125 - val_loss: 15.4928
Epoch 27/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2637 - loss: 23.0376 - val_accuracy: 0.6243 - val_loss: 15.7607
Epoch 28/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2806 - loss: 22.8811 - val_accuracy: 0.6074 - val_loss: 14.1576
Epoch 29/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2585 - loss: 22.4246 - val_accuracy: 0.6196 - val_loss: 13.5118
Epoch 30/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.2443 - loss: 23.1006 - val_accuracy: 0.6145 - val_loss: 15.9970

The loss keeps being around 24.5, and the accuracy around 0.2, so the model is not converging

In [131]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

216/216 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BUDAPEST  DEBILT  MAASTRICHT  MADRID  OSLO
True
BASEL              9       0           0       0     0
BUDAPEST        4230       2         149       1    65
DEBILT            71       0           0       0     0
DUSSELDORF       245       0           0       0     0
HEATHROW          99       0           0       0     0
KASSEL             4       0           0       0     0
LJUBLJANA          3       0           0       0     0
MAASTRICHT      1304       0           1       0     0
MADRID            13       0           0       0     0
MUNCHENB           7       0           0       0     0
OSLO             546       0           0       0     0
SONNBLICK          8       0           0       0     0
STOCKHOLM         32       0           0       0     0
VALENTIA          96       0           0       0     0

#### - 2nd iteration
<div id='2.3.2'></div>

In [133]:
# 2nd iteration - hidden layers up to 64

epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh'))

In [134]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_6 (LSTM)                        │ (None, 64)                  │          18,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_6 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 15)                  │             975 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,919 (77.81 KB)

 Trainable params: 19,919 (77.81 KB)

 Non-trainable params: 0 (0.00 B)

In [135]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [136]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.2028 - loss: 24.8147 - val_accuracy: 0.0697 - val_loss: 26.6882
Epoch 2/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0499 - loss: 24.8326 - val_accuracy: 0.0118 - val_loss: 23.2780
Epoch 3/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0381 - loss: 24.5804 - val_accuracy: 0.0110 - val_loss: 25.5025
Epoch 4/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0280 - loss: 25.3163 - val_accuracy: 0.0141 - val_loss: 26.1523
Epoch 5/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0321 - loss: 24.7838 - val_accuracy: 0.0023 - val_loss: 16.3774
Epoch 6/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0462 - loss: 24.8654 - val_accuracy: 0.0029 - val_loss: 27.0348
Epoch 7/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0767 - loss: 25.1296 - val_accuracy: 0.1699 - val_loss: 26.6993
Epoch 8/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0750 - loss: 25.2311 - val_accuracy: 0.1795 - val_loss: 26.7232
Epoch 9/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0940 - loss: 24.6858 - val_accuracy: 0.1344 - val_loss: 24.0367
Epoch 10/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.1197 - loss: 24.8637 - val_accuracy: 0.0810 - val_loss: 24.8014
Epoch 11/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0921 - loss: 24.8558 - val_accuracy: 0.0999 - val_loss: 29.9730
Epoch 12/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0937 - loss: 24.4768 - val_accuracy: 0.0837 - val_loss: 19.3350
Epoch 13/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0920 - loss: 24.4684 - val_accuracy: 0.0090 - val_loss: 24.5569
Epoch 14/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.1012 - loss: 24.3243 - val_accuracy: 0.0763 - val_loss: 25.4831
Epoch 15/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.1329 - loss: 24.1027 - val_accuracy: 0.0022 - val_loss: 25.5644
Epoch 16/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0889 - loss: 23.9272 - val_accuracy: 0.0975 - val_loss: 26.3049
Epoch 17/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0660 - loss: 23.0245 - val_accuracy: 0.0012 - val_loss: 25.3701
Epoch 18/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0515 - loss: 20.5380 - val_accuracy: 4.3573e-04 - val_loss: 26.6068
Epoch 19/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0260 - loss: 21.6071 - val_accuracy: 0.0131 - val_loss: 24.5537
Epoch 20/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0557 - loss: 21.3975 - val_accuracy: 0.0116 - val_loss: 24.5949
Epoch 21/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0609 - loss: 22.6917 - val_accuracy: 0.0015 - val_loss: 24.4733
Epoch 22/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0744 - loss: 21.3345 - val_accuracy: 0.0044 - val_loss: 24.8151
Epoch 23/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0703 - loss: 21.8997 - val_accuracy: 4.3573e-04 - val_loss: 24.5693
Epoch 24/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0566 - loss: 21.8403 - val_accuracy: 0.0010 - val_loss: 25.3559
Epoch 25/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0806 - loss: 23.0403 - val_accuracy: 4.3573e-04 - val_loss: 26.0231
Epoch 26/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.0625 - loss: 22.9643 - val_accuracy: 5.8097e-04 - val_loss: 24.5599
Epoch 27/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0641 - loss: 21.5986 - val_accuracy: 0.0022 - val_loss: 24.6933
Epoch 28/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0811 - loss: 23.6845 - val_accuracy: 0.0019 - val_loss: 24.5435
Epoch 29/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0890 - loss: 23.8105 - val_accuracy: 5.8097e-04 - val_loss: 26.8003
Epoch 30/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0873 - loss: 23.1637 - val_accuracy: 5.8097e-04 - val_loss: 24.5342

The loss is about the same but the accuracy went down to around 0.07

In [138]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

216/216 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        DUSSELDORF  HEATHROW  KASSEL  LJUBLJANA  MAASTRICHT  SONNBLICK  \
True
BASEL                0         0       0          9           0          0
BUDAPEST             1         4       3       4206         231          1
DEBILT               0         0       0         71           0          0
DUSSELDORF           0         0       0        245           0          0
HEATHROW             0         0       0         99           0          0
KASSEL               0         0       0          4           0          0
LJUBLJANA            0         0       0          3           0          0
MAASTRICHT           0         0       0       1304           1          0
MADRID               0         0       0         13           0          0
MUNCHENB             0         0       0          7           0          0
OSLO                 0         0       0        546           0          0
SONNBLICK            0         0       0          8           0          0
STOCKHOLM            0         0       0         32           0          0
VALENTIA             0         0       0         96           0          0

Pred        VALENTIA
True
BASEL              0
BUDAPEST           1
DEBILT             0
DUSSELDORF         0
HEATHROW           0
KASSEL             0
LJUBLJANA          0
MAASTRICHT         0
MADRID             0
MUNCHENB           0
OSLO               0
SONNBLICK          0
STOCKHOLM          0
VALENTIA           0

#### - 3rd iteration
<div id='2.3.3'></div>

In [140]:
# 3rd iteration - trying with a different activation : sigmoid

epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [141]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_7 (LSTM)                        │ (None, 64)                  │          18,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_7 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 15)                  │             975 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,919 (77.81 KB)

 Trainable params: 19,919 (77.81 KB)

 Non-trainable params: 0 (0.00 B)

In [142]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [143]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.1025 - loss: 11.0726 - val_accuracy: 0.0434 - val_loss: 9.5271
Epoch 2/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0839 - loss: 11.5585 - val_accuracy: 0.0447 - val_loss: 9.9595
Epoch 3/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0938 - loss: 11.7434 - val_accuracy: 0.0389 - val_loss: 10.3483
Epoch 4/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0884 - loss: 12.1717 - val_accuracy: 0.0346 - val_loss: 11.0780
Epoch 5/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0857 - loss: 12.5720 - val_accuracy: 0.0411 - val_loss: 11.8387
Epoch 6/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0835 - loss: 13.1968 - val_accuracy: 0.0452 - val_loss: 12.4845
Epoch 7/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0760 - loss: 13.7980 - val_accuracy: 0.0404 - val_loss: 13.1341
Epoch 8/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.0767 - loss: 14.4811 - val_accuracy: 0.0793 - val_loss: 13.8840
Epoch 9/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0815 - loss: 14.7153 - val_accuracy: 0.0793 - val_loss: 14.2122
Epoch 10/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0746 - loss: 15.5282 - val_accuracy: 0.0793 - val_loss: 15.1996
Epoch 11/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0659 - loss: 15.7420 - val_accuracy: 0.0431 - val_loss: 15.7207
Epoch 12/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0696 - loss: 16.6357 - val_accuracy: 0.0559 - val_loss: 16.2287
Epoch 13/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0648 - loss: 17.4252 - val_accuracy: 0.0793 - val_loss: 16.7207
Epoch 14/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0619 - loss: 17.5853 - val_accuracy: 0.0784 - val_loss: 17.2934
Epoch 15/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0689 - loss: 18.4673 - val_accuracy: 0.0508 - val_loss: 18.2348
Epoch 16/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.0590 - loss: 19.3242 - val_accuracy: 0.0353 - val_loss: 18.7479
Epoch 17/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0577 - loss: 19.7656 - val_accuracy: 0.0399 - val_loss: 19.3571
Epoch 18/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0563 - loss: 19.8710 - val_accuracy: 0.0519 - val_loss: 20.2934
Epoch 19/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0510 - loss: 21.2362 - val_accuracy: 0.0478 - val_loss: 20.3743
Epoch 20/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0534 - loss: 21.2975 - val_accuracy: 0.0311 - val_loss: 20.9111
Epoch 21/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0514 - loss: 22.5111 - val_accuracy: 0.0394 - val_loss: 21.3950
Epoch 22/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0570 - loss: 21.5433 - val_accuracy: 0.0546 - val_loss: 21.8861
Epoch 23/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0584 - loss: 22.6393 - val_accuracy: 0.0534 - val_loss: 22.3427
Epoch 24/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0595 - loss: 23.3191 - val_accuracy: 0.0794 - val_loss: 22.6404
Epoch 25/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0528 - loss: 23.7701 - val_accuracy: 0.0794 - val_loss: 23.1994
Epoch 26/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0590 - loss: 24.7950 - val_accuracy: 0.0370 - val_loss: 24.0453
Epoch 27/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0508 - loss: 24.9268 - val_accuracy: 0.0793 - val_loss: 24.4019
Epoch 28/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0645 - loss: 25.0515 - val_accuracy: 0.0460 - val_loss: 24.7647
Epoch 29/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0578 - loss: 26.4904 - val_accuracy: 0.0469 - val_loss: 25.5363
Epoch 30/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0563 - loss: 26.4720 - val_accuracy: 0.0540 - val_loss: 26.2026

The accuracy decreases and the loss increases, so the sigmoid activation isn't performing well either

In [145]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

216/216 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BUDAPEST  OSLO
True
BASEL              9     0
BUDAPEST        4446     1
DEBILT            71     0
DUSSELDORF       245     0
HEATHROW          99     0
KASSEL             4     0
LJUBLJANA          3     0
MAASTRICHT      1305     0
MADRID            13     0
MUNCHENB           7     0
OSLO             545     1
SONNBLICK          8     0
STOCKHOLM         32     0
VALENTIA          96     0

#### - 4th iteration
<div id='2.3.4'></div>

In [193]:
# 4th iteration - low hidden layers seems to work a bit best, let's try out another activation 

epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='softmax'))

In [195]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_10 (LSTM)                       │ (None, 32)                  │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_10 (Dropout)                 │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 15)                  │             495 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,871 (22.93 KB)

 Trainable params: 5,871 (22.93 KB)

 Non-trainable params: 0 (0.00 B)

In [197]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [199]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.0870 - loss: 10.3857 - val_accuracy: 0.0417 - val_loss: 9.1933
Epoch 2/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0873 - loss: 10.7292 - val_accuracy: 0.0376 - val_loss: 9.4062
Epoch 3/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0857 - loss: 10.8789 - val_accuracy: 0.0475 - val_loss: 9.6735
Epoch 4/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0874 - loss: 11.0756 - val_accuracy: 0.0388 - val_loss: 10.2608
Epoch 5/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0881 - loss: 11.0435 - val_accuracy: 0.0324 - val_loss: 10.5949
Epoch 6/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0814 - loss: 11.7127 - val_accuracy: 0.0482 - val_loss: 10.8931
Epoch 7/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0750 - loss: 11.8164 - val_accuracy: 0.0376 - val_loss: 11.1045
Epoch 8/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.0739 - loss: 11.9314 - val_accuracy: 0.0473 - val_loss: 11.4839
Epoch 9/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0713 - loss: 12.3142 - val_accuracy: 0.0174 - val_loss: 11.8289
Epoch 10/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0705 - loss: 12.5816 - val_accuracy: 0.0408 - val_loss: 12.0480
Epoch 11/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0701 - loss: 12.5956 - val_accuracy: 0.0229 - val_loss: 12.2892
Epoch 12/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0638 - loss: 12.8322 - val_accuracy: 0.0582 - val_loss: 12.6421
Epoch 13/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0568 - loss: 13.5011 - val_accuracy: 0.0306 - val_loss: 12.9650
Epoch 14/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0581 - loss: 13.5205 - val_accuracy: 0.0386 - val_loss: 13.0630
Epoch 15/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0599 - loss: 13.9551 - val_accuracy: 0.0465 - val_loss: 13.3896
Epoch 16/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0545 - loss: 13.9839 - val_accuracy: 0.0449 - val_loss: 13.6136
Epoch 17/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0526 - loss: 14.0786 - val_accuracy: 0.0286 - val_loss: 13.8815
Epoch 18/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0466 - loss: 14.3748 - val_accuracy: 0.0434 - val_loss: 14.2941
Epoch 19/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0495 - loss: 14.8838 - val_accuracy: 0.0290 - val_loss: 14.4868
Epoch 20/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0501 - loss: 15.2435 - val_accuracy: 0.0433 - val_loss: 14.8683
Epoch 21/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0552 - loss: 15.5532 - val_accuracy: 0.0421 - val_loss: 14.9713
Epoch 22/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.0496 - loss: 15.5775 - val_accuracy: 0.0456 - val_loss: 15.4199
Epoch 23/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0469 - loss: 16.0187 - val_accuracy: 0.0520 - val_loss: 15.5023
Epoch 24/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0497 - loss: 16.4984 - val_accuracy: 0.0436 - val_loss: 15.7445
Epoch 25/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0489 - loss: 16.6609 - val_accuracy: 0.0487 - val_loss: 16.0800
Epoch 26/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0543 - loss: 16.5482 - val_accuracy: 0.0408 - val_loss: 16.3868
Epoch 27/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0491 - loss: 16.9599 - val_accuracy: 0.0385 - val_loss: 16.2284
Epoch 28/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0512 - loss: 16.8120 - val_accuracy: 0.0333 - val_loss: 16.4626
Epoch 29/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0507 - loss: 17.5947 - val_accuracy: 0.0408 - val_loss: 16.7338
Epoch 30/30
1005/1005 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0484 - loss: 17.6428 - val_accuracy: 0.0446 - val_loss: 17.1240

In [200]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

216/216 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        DUSSELDORF  HEATHROW  LJUBLJANA  MUNCHENB  OSLO  SONNBLICK
True
BASEL                0         0          3         2     4          0
BUDAPEST             3         0       2605        89  1748          2
DEBILT               0         0          0         7    64          0
DUSSELDORF           0         0          3        11   231          0
HEATHROW             0         0          5         5    89          0
KASSEL               0         0          0         0     4          0
LJUBLJANA            0         0          1         1     1          0
MAASTRICHT           2         0         75        55  1172          1
MADRID               0         0          0         0    13          0
MUNCHENB             0         1          0         0     6          0
OSLO                 2         1        184        52   306          1
SONNBLICK            1         0          1         2     4          0
STOCKHOLM            0         0          3         1    28          0
VALENTIA             0         0          0         0    96          0

Loss increases and accuracy decreases, Tanh activation is the best so far.

#### - 5th iteration
<div id='2.3.5'></div>

In [204]:
# 5th iteration - reducing the hidden layers one more time, and increasing both the batch size and the epoch

epochs = 60
batch_size = 32
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh'))

In [206]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_11 (LSTM)                       │ (None, 16)                  │           1,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_11 (Dropout)                 │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 15)                  │             255 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,919 (7.50 KB)

 Trainable params: 1,919 (7.50 KB)

 Non-trainable params: 0 (0.00 B)

In [208]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [210]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0475 - loss: 24.9864 - val_accuracy: 0.0020 - val_loss: 31.4921
Epoch 2/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0349 - loss: 23.7801 - val_accuracy: 0.0052 - val_loss: 23.8860
Epoch 3/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0220 - loss: 22.7939 - val_accuracy: 0.0042 - val_loss: 24.5609
Epoch 4/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0090 - loss: 22.6764 - val_accuracy: 1.4524e-04 - val_loss: 27.5374
Epoch 5/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0074 - loss: 21.9223 - val_accuracy: 0.0000e+00 - val_loss: 26.2338
Epoch 6/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0092 - loss: 22.0665 - val_accuracy: 1.4524e-04 - val_loss: 26.4789
Epoch 7/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0106 - loss: 22.4098 - val_accuracy: 0.0013 - val_loss: 24.4627
Epoch 8/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0178 - loss: 22.4642 - val_accuracy: 0.0523 - val_loss: 15.9485
Epoch 9/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0354 - loss: 21.2780 - val_accuracy: 0.0571 - val_loss: 14.0131
Epoch 10/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0281 - loss: 21.5763 - val_accuracy: 0.0225 - val_loss: 14.1588
Epoch 11/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0213 - loss: 21.2099 - val_accuracy: 0.0571 - val_loss: 19.0097
Epoch 12/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0221 - loss: 22.3695 - val_accuracy: 0.0414 - val_loss: 17.7629
Epoch 13/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0227 - loss: 22.3403 - val_accuracy: 0.0330 - val_loss: 36.4950
Epoch 14/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0209 - loss: 22.1085 - val_accuracy: 0.0016 - val_loss: 34.7431
Epoch 15/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0204 - loss: 20.8093 - val_accuracy: 0.0016 - val_loss: 17.0592
Epoch 16/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0251 - loss: 20.5609 - val_accuracy: 0.0022 - val_loss: 16.5714
Epoch 17/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0225 - loss: 19.8693 - val_accuracy: 0.0032 - val_loss: 16.5222
Epoch 18/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0247 - loss: 19.5460 - val_accuracy: 0.0032 - val_loss: 16.5812
Epoch 19/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0205 - loss: 19.4886 - val_accuracy: 0.0022 - val_loss: 16.6169
Epoch 20/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0200 - loss: 19.3263 - val_accuracy: 0.0022 - val_loss: 16.5569
Epoch 21/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0232 - loss: 19.6919 - val_accuracy: 0.0023 - val_loss: 16.6305
Epoch 22/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0226 - loss: 19.6715 - val_accuracy: 0.0023 - val_loss: 16.5578
Epoch 23/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0222 - loss: 19.8306 - val_accuracy: 0.0022 - val_loss: 16.5655
Epoch 24/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0225 - loss: 19.2525 - val_accuracy: 0.0022 - val_loss: 16.5655
Epoch 25/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0238 - loss: 19.5993 - val_accuracy: 0.0022 - val_loss: 16.5457
Epoch 26/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0271 - loss: 19.6961 - val_accuracy: 0.0023 - val_loss: 16.5690
Epoch 27/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0212 - loss: 19.5152 - val_accuracy: 0.0016 - val_loss: 16.5408
Epoch 28/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0233 - loss: 19.4327 - val_accuracy: 0.0016 - val_loss: 16.5420
Epoch 29/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0268 - loss: 19.4014 - val_accuracy: 0.0016 - val_loss: 16.5325
Epoch 30/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0204 - loss: 19.2755 - val_accuracy: 0.0016 - val_loss: 16.5325
Epoch 31/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0229 - loss: 19.2322 - val_accuracy: 0.0016 - val_loss: 16.5301
Epoch 32/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0221 - loss: 19.5375 - val_accuracy: 0.0016 - val_loss: 16.5482
Epoch 33/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0198 - loss: 19.0523 - val_accuracy: 0.0017 - val_loss: 16.5359
Epoch 34/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0223 - loss: 19.3259 - val_accuracy: 0.0015 - val_loss: 16.5280
Epoch 35/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0187 - loss: 19.5360 - val_accuracy: 0.0015 - val_loss: 16.5348
Epoch 36/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0214 - loss: 19.0326 - val_accuracy: 0.0016 - val_loss: 34.8418
Epoch 37/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0233 - loss: 19.1293 - val_accuracy: 0.0016 - val_loss: 16.5390
Epoch 38/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0196 - loss: 18.9990 - val_accuracy: 0.0016 - val_loss: 16.5279
Epoch 39/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0247 - loss: 19.3720 - val_accuracy: 0.0016 - val_loss: 34.8418
Epoch 40/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0230 - loss: 20.1938 - val_accuracy: 0.0016 - val_loss: 34.8418
Epoch 41/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0272 - loss: 19.9036 - val_accuracy: 0.0016 - val_loss: 23.2069
Epoch 42/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0266 - loss: 19.8436 - val_accuracy: 0.0016 - val_loss: 16.5427
Epoch 43/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0276 - loss: 19.2797 - val_accuracy: 0.0016 - val_loss: 16.5512
Epoch 44/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0259 - loss: 19.1523 - val_accuracy: 0.0016 - val_loss: 34.8259
Epoch 45/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.0270 - loss: 20.2590 - val_accuracy: 0.0016 - val_loss: 34.8259
Epoch 46/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0262 - loss: 19.6351 - val_accuracy: 0.0016 - val_loss: 34.8259
Epoch 47/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0260 - loss: 20.0287 - val_accuracy: 0.0016 - val_loss: 34.8259
Epoch 48/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0246 - loss: 19.2588 - val_accuracy: 0.0016 - val_loss: 16.5418
Epoch 49/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0258 - loss: 19.2336 - val_accuracy: 0.0016 - val_loss: 16.5418
Epoch 50/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0290 - loss: 19.4806 - val_accuracy: 0.0016 - val_loss: 16.5418
Epoch 51/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0224 - loss: 19.1657 - val_accuracy: 0.0016 - val_loss: 16.5418
Epoch 52/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0213 - loss: 19.4963 - val_accuracy: 0.0016 - val_loss: 16.5418
Epoch 53/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0244 - loss: 20.3676 - val_accuracy: 0.0016 - val_loss: 34.8349
Epoch 54/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0276 - loss: 20.3328 - val_accuracy: 0.0022 - val_loss: 16.5448
Epoch 55/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0261 - loss: 19.3803 - val_accuracy: 0.0016 - val_loss: 16.5372
Epoch 56/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0245 - loss: 19.1111 - val_accuracy: 0.0019 - val_loss: 27.3086
Epoch 57/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0244 - loss: 19.3452 - val_accuracy: 0.0025 - val_loss: 34.4570
Epoch 58/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0263 - loss: 19.8294 - val_accuracy: 0.0022 - val_loss: 16.8467
Epoch 59/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0240 - loss: 18.9360 - val_accuracy: 0.0022 - val_loss: 16.8467
Epoch 60/60
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0224 - loss: 19.3261 - val_accuracy: 0.0039 - val_loss: 22.9863

The loss decreases but the accuracy isn't doing better

In [211]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

216/216 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Pred        BASEL  BELGRADE  HEATHROW  KASSEL  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL           0         0         0       0         9     0          0
BUDAPEST        3         2       109       6      3391   934          1
DEBILT          0         0         0       0        71     0          0
DUSSELDORF      0         0         0       0       245     0          0
HEATHROW        0         0         0       0        99     0          0
KASSEL          0         0         0       0         4     0          0
LJUBLJANA       0         0         0       0         3     0          0
MAASTRICHT      0         0         0       0      1304     1          0
MADRID          0         0         0       0        13     0          0
MUNCHENB        0         0         0       0         7     0          0
OSLO            0         0         2       0       524    20          0
SONNBLICK       0         0         0       0         8     0          0
STOCKHOLM       0         0         0       0        32     0          0
VALENTIA        0         0         0       0        96     0          0

Pred        STOCKHOLM
True
BASEL               0
BUDAPEST            1
DEBILT              0
DUSSELDORF          0
HEATHROW            0
KASSEL              0
LJUBLJANA           0
MAASTRICHT          0
MADRID              0
MUNCHENB            0
OSLO                0
SONNBLICK           0
STOCKHOLM           0
VALENTIA            0